title: Arrow Executive Sales
email: "hello@arrowexec.com.au"
phone: "1300 903 527"
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arrowexec.com.au" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-165678042-1

# Permalinks
permalink: pretty
permalink: /articles/:title/

include:
  - _pages
  - _redirects
  
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - assets/scss
  - vendor