title: Arrow Executive Sales
email: "hello@arrowexec.com.au"
phone: "0435 049 140"
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arrowexecsales.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com


# Permalinks
permalink: pretty
permalink: /articles/:title/

include:
  - _pages
  - _redirects
  
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - css
  - gulpfile.js
  - assets/scss
  - vendor