services:
  jekyll:
    image: arrow-image
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/_site
    ports:
      - "4000:4000"
      - '35729:35729'
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --livereload --force_polling